name: Build and Release
 
on:
  push:
    tags:
      - 'v*' # 当推送 v 开头的标签时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build-win:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - os: windows-2019
            arch: x64
            opencv_version: 4.5.5
            arch_name: x64

    steps:
    - uses: actions/checkout@v3

    - name: Check Environment
      shell: pwsh
      run: |
        Write-Host "Workflow: $env:GITHUB_WORKFLOW"
        Write-Host "JAVA_HOME_8_X64: $env:JAVA_HOME_8_X64"
        dir C:\
        which vcpkg
        which cmake
        which git
        which python
        which pip
        which ninja
        which java
        which ant

    - name: Build
      shell: pwsh
      run: ./build-opencv.ps1

    - name: Create Github Release
      id: create_release
      uses: softprops/action-gh-release@v2.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: C:/opencv-${{ matrix.opencv_version }}-${{ matrix.arch_name }}.zip
  build-linux:
    runs-on: ${{ matrix.os }}
    env:
      REPO_PATH: ${{ github.workspace }}
    container:
      image: debian:10
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            opencv_version: 4.5.5
            arch_name: x86_64
          - os: ubuntu-24.04-arm #ubuntu-latest-arm
            arch: arm64
            arch_name: aarch64
            opencv_version: 4.5.5

    steps:
    - name: Check Environment
      run: |
        uname -a
        ldd --version

    - uses: actions/checkout@v3
    
    - name: Build
      run: |
        chmod +x ./build-opencv.sh
        ./build-opencv.sh

    - name: Create Github Release
      id: create_release
      uses: softprops/action-gh-release@v2.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: /github/home/opencv_build/opencv-linux-${{ matrix.opencv_version }}-${{ matrix.arch_name }}.tar.gz